name: Release
on:
  push:
    branches: ["master", "environment/*"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: get-version
        name: Get version
        run: |
          version=$(cat pyproject.toml | grep -m 1 "^version =" | awk '{print $3}' | sed 's/"//g')
          echo "Version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if version tag exists
        run: |
          TAG="${{ steps.get-version.outputs.version }}"
          if [ $(git tag -l $TAG) ]; then
            echo "Tag $TAG exists"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG does not exist"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

  # Deploy-Dev:
  #   runs-on: ubuntu-latest
  #   needs: Build
  #   environment:
  #     name: "dev"
  #     url: "https://github.com"
  #   steps:
  #     - name: "no-op"
  #       run: echo "NO-OP"

  # Deploy-Staging:
  #   runs-on: ubuntu-latest
  #   needs: Deploy-Dev
  #   environment:
  #     name: "staging"
  #     url: "https://github.com"
  #   steps:
  #     - name: "no-op"
  #       run: echo "NO-OP"

  # Deploy-Prod:
  #   runs-on: ubuntu-latest
  #   needs: Deploy-Staging
  #   environment:
  #     name: "prod"
  #     url: "https://github.com"
  #   steps:
  #     - name: "no-op"
  #       run: echo "NO-OP"
