on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: dump github context
        run: echo "${{ toJSON(github) }}"
