name: Release hotfix
run-name: "Deploy ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Container image version"
        required: true
      environment:
        description: "Environment name"
        required: true
        default: "bg-staging"
        type: choice
        options:
          - bg-staging
          - bg-test
          - maas-staging
          - maas

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install OS deps
        run: |
          sudo apt-get update \
          && sudo apt-get install -y build-essential \
          && sudo apt-get install -y libpq-dev \
          && sudo apt-get install -y gettext \
          && sudo apt-get install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl \
          && sudo apt-get install -y python3-pydot python3-pydot-ng graphviz \
          && sudo apt-get install -y binutils libproj-dev gdal-bin \
          && sudo apt-get install -y git \
          && sudo apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
          && sudo rm -rf /var/lib/apt/lists/*
