name: Release hotfix
run-name: "Deploy ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Container image version"
        required: true
      environment:
        description: "Environment name"
        required: true
        default: "bg-staging"
        type: choice
        options:
          - bg-staging
          - bg-test
          - maas-staging
          - maas

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.version }}"
